/*
 * Copyright (c) 2023 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import {
  Entity,
  DefaultDeSerializers,
  DeSerializers,
  DeserializedType
} from '@sap-cloud-sdk/odata-v4';
import { CampaignBusinessPartner } from './CampaignBusinessPartner';
import { CampaignItem } from './CampaignItem';
import { CampaignPartner } from './CampaignPartner';
import type { CampaignsApi } from './CampaignsApi';
import { CampaignTypeEnum } from './CampaignTypeEnum';
import { CampaignStatusEnum } from './CampaignStatusEnum';
import { BoYesNoEnum } from './BoYesNoEnum';
import { TargetGroupTypeEnum } from './TargetGroupTypeEnum';
import { TargetGroups, TargetGroupsType } from './TargetGroups';
import { EmployeesInfo, EmployeesInfoType } from './EmployeesInfo';
import { Attachments2, Attachments2Type } from './Attachments2';
import { BusinessPartners, BusinessPartnersType } from './BusinessPartners';

/**
 * This class represents the entity "Campaigns" of service "SAPB1".
 */
export class Campaigns<T extends DeSerializers = DefaultDeSerializers>
  extends Entity
  implements CampaignsType<T>
{
  /**
   * Technical entity name for Campaigns.
   */
  static _entityName = 'Campaigns';
  /**
   * Default url path for the according service.
   */
  static _defaultBasePath = '/';
  /**
   * All key fields of the Campaigns entity
   */
  static _keys = ['CampaignNumber'];
  /**
   * Campaign Number.
   */
  campaignNumber!: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Campaign Name.
   * @nullable
   */
  campaignName?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Campaign Type.
   * @nullable
   */
  campaignType?: CampaignTypeEnum | null;
  /**
   * Target Group.
   * @nullable
   */
  targetGroup?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Owner.
   * @nullable
   */
  owner?: DeserializedType<T, 'Edm.Int32'> | null;
  /**
   * Status.
   * @nullable
   */
  status?: CampaignStatusEnum | null;
  /**
   * Start Date.
   * @nullable
   */
  startDate?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  /**
   * Finish Date.
   * @nullable
   */
  finishDate?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  /**
   * Remarks.
   * @nullable
   */
  remarks?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Generated By Wizard.
   * @nullable
   */
  generatedByWizard?: BoYesNoEnum | null;
  /**
   * Attachements Entry.
   * @nullable
   */
  attachementsEntry?: DeserializedType<T, 'Edm.Int32'> | null;
  /**
   * Target Group Type.
   * @nullable
   */
  targetGroupType?: TargetGroupTypeEnum | null;
  /**
   * U Ziel.
   * @nullable
   */
  uZiel?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Zielgruppe.
   * @nullable
   */
  uZielgruppe?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Produkt.
   * @nullable
   */
  uProdukt?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Stufe 1.
   * @nullable
   */
  uStufe1?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Stufe 1 Datum.
   * @nullable
   */
  uStufe1Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  /**
   * U Stufe 2.
   * @nullable
   */
  uStufe2?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Stufe 2 Datum.
   * @nullable
   */
  uStufe2Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  /**
   * U Stufe 3.
   * @nullable
   */
  uStufe3?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Stufe 3 Datum.
   * @nullable
   */
  uStufe3Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  /**
   * U Stufe 4.
   * @nullable
   */
  uStufe4?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Stufe 4 Datum.
   * @nullable
   */
  uStufe4Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  /**
   * U Stufe 5.
   * @nullable
   */
  uStufe5?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * U Stufe 5 Datum.
   * @nullable
   */
  uStufe5Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  /**
   * U Umsatz.
   * @nullable
   */
  uUmsatz?: DeserializedType<T, 'Edm.Int32'> | null;
  /**
   * U Db.
   * @nullable
   */
  uDb?: DeserializedType<T, 'Edm.Int32'> | null;
  /**
   * U Kosten.
   * @nullable
   */
  uKosten?: DeserializedType<T, 'Edm.Int32'> | null;
  /**
   * U Status.
   * @nullable
   */
  uStatus?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Campaign Business Partners.
   * @nullable
   */
  campaignBusinessPartners?: CampaignBusinessPartner<T>[] | null;
  /**
   * Campaign Items.
   * @nullable
   */
  campaignItems?: CampaignItem<T>[] | null;
  /**
   * Campaign Partners.
   * @nullable
   */
  campaignPartners?: CampaignPartner<T>[] | null;
  /**
   * One-to-one navigation property to the {@link TargetGroups} entity.
   */
  targetGroup2?: TargetGroups<T> | null;
  /**
   * One-to-one navigation property to the {@link EmployeesInfo} entity.
   */
  employeeInfo?: EmployeesInfo<T> | null;
  /**
   * One-to-one navigation property to the {@link Attachments2} entity.
   */
  attachments2?: Attachments2<T> | null;
  /**
   * One-to-many navigation property to the {@link BusinessPartners} entity.
   */
  businessPartners!: BusinessPartners<T>[];

  constructor(readonly _entityApi: CampaignsApi<T>) {
    super(_entityApi);
  }
}

export interface CampaignsType<T extends DeSerializers = DefaultDeSerializers> {
  campaignNumber: DeserializedType<T, 'Edm.Int32'>;
  campaignName?: DeserializedType<T, 'Edm.String'> | null;
  campaignType?: CampaignTypeEnum | null;
  targetGroup?: DeserializedType<T, 'Edm.String'> | null;
  owner?: DeserializedType<T, 'Edm.Int32'> | null;
  status?: CampaignStatusEnum | null;
  startDate?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  finishDate?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  remarks?: DeserializedType<T, 'Edm.String'> | null;
  generatedByWizard?: BoYesNoEnum | null;
  attachementsEntry?: DeserializedType<T, 'Edm.Int32'> | null;
  targetGroupType?: TargetGroupTypeEnum | null;
  uZiel?: DeserializedType<T, 'Edm.String'> | null;
  uZielgruppe?: DeserializedType<T, 'Edm.String'> | null;
  uProdukt?: DeserializedType<T, 'Edm.String'> | null;
  uStufe1?: DeserializedType<T, 'Edm.String'> | null;
  uStufe1Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  uStufe2?: DeserializedType<T, 'Edm.String'> | null;
  uStufe2Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  uStufe3?: DeserializedType<T, 'Edm.String'> | null;
  uStufe3Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  uStufe4?: DeserializedType<T, 'Edm.String'> | null;
  uStufe4Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  uStufe5?: DeserializedType<T, 'Edm.String'> | null;
  uStufe5Datum?: DeserializedType<T, 'Edm.DateTimeOffset'> | null;
  uUmsatz?: DeserializedType<T, 'Edm.Int32'> | null;
  uDb?: DeserializedType<T, 'Edm.Int32'> | null;
  uKosten?: DeserializedType<T, 'Edm.Int32'> | null;
  uStatus?: DeserializedType<T, 'Edm.String'> | null;
  campaignBusinessPartners?: CampaignBusinessPartner<T>[] | null;
  campaignItems?: CampaignItem<T>[] | null;
  campaignPartners?: CampaignPartner<T>[] | null;
  targetGroup2?: TargetGroupsType<T> | null;
  employeeInfo?: EmployeesInfoType<T> | null;
  attachments2?: Attachments2Type<T> | null;
  businessPartners: BusinessPartnersType<T>[];
}
