export declare enum ApprovalTemplatesDocumentTypeEnum {
    atdtQuotation = "atdtQuotation",
    atdtOrder = "atdtOrder",
    atdtDelivery = "atdtDelivery",
    atdtReturns = "atdtReturns",
    atdtArDownPayment = "atdtArDownPayment",
    atdtArInvoice = "atdtArInvoice",
    atdtArCreditMemo = "atdtArCreditMemo",
    atdtCorrectionInvoice = "atdtCorrectionInvoice",
    atdtPurchaseOrder = "atdtPurchaseOrder",
    atdtGoodsReceiptPO = "atdtGoodsReceiptPO",
    atdtGoodsReturns = "atdtGoodsReturns",
    atdtApDownPayment = "atdtApDownPayment",
    atdtApInvoice = "atdtApInvoice",
    atdtApCreditMemo = "atdtApCreditMemo",
    atdtGoodsReceipt = "atdtGoodsReceipt",
    atdtGoodsIssue = "atdtGoodsIssue",
    atdtInventoryTransfer = "atdtInventoryTransfer",
    atdtPurchaseQuotation = "atdtPurchaseQuotation",
    atdtInventoryTransferRequest = "atdtInventoryTransferRequest",
    atdtOutgoingPayment = "atdtOutgoingPayment",
    atdtInventoryCounting = "atdtInventoryCounting",
    atdtInventoryPosting = "atdtInventoryPosting",
    atdtInventoryOpeningBalance = "atdtInventoryOpeningBalance"
}
//# sourceMappingURL=ApprovalTemplatesDocumentTypeEnum.d.ts.map