/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */

export enum BoChangeLogEnum {
  clChartOfAccounts = 'clChartOfAccounts',
  clBusinessPartners = 'clBusinessPartners',
  clItems = 'clItems',
  clVatGroups = 'clVatGroups',
  clUsers = 'clUsers',
  clInvoices = 'clInvoices',
  clCreditNotes = 'clCreditNotes',
  clDeliveryNotes = 'clDeliveryNotes',
  clReturns = 'clReturns',
  clOrders = 'clOrders',
  clPurchaseInvoices = 'clPurchaseInvoices',
  clPurchaseCreditNotes = 'clPurchaseCreditNotes',
  clPurchaseDeliveryNotes = 'clPurchaseDeliveryNotes',
  clPurchaseReturns = 'clPurchaseReturns',
  clPurchaseOrders = 'clPurchaseOrders',
  clQuotations = 'clQuotations',
  clIncomingPayments = 'clIncomingPayments',
  clJournalEntries = 'clJournalEntries',
  clCreditCards = 'clCreditCards',
  clAdminInfo = 'clAdminInfo',
  clVendorPayments = 'clVendorPayments',
  clItemGroups = 'clItemGroups',
  clInventoryGeneralEntry = 'clInventoryGeneralEntry',
  clInventoryGeneralExit = 'clInventoryGeneralExit',
  clWarehouses = 'clWarehouses',
  clProductTrees = 'clProductTrees',
  clStockTransfers = 'clStockTransfers',
  clFinancePeriods = 'clFinancePeriods',
  clAdditionalExpenses = 'clAdditionalExpenses',
  clPickLists = 'clPickLists',
  clMaterialRevaluation = 'clMaterialRevaluation',
  clCorrectionPurchaseInvoice = 'clCorrectionPurchaseInvoice',
  clCorrectionPurchaseInvoiceReversal = 'clCorrectionPurchaseInvoiceReversal',
  clCorrectionInvoice = 'clCorrectionInvoice',
  clCorrectionInvoiceReversal = 'clCorrectionInvoiceReversal',
  clEmployeesInfo = 'clEmployeesInfo',
  clCustomerEquipmentCards = 'clCustomerEquipmentCards',
  clWithholdingTaxCodes = 'clWithholdingTaxCodes',
  clBillOfExchange = 'clBillOfExchange',
  clServiceCalls = 'clServiceCalls',
  clProductionOrders = 'clProductionOrders',
  clDownPayments = 'clDownPayments',
  clPurchaseDownPayments = 'clPurchaseDownPayments',
  clPeriodCategory = 'clPeriodCategory',
  clHouseBankAccounts = 'clHouseBankAccounts',
  clSalesTaxInvoice = 'clSalesTaxInvoice',
  clPurchaseTaxInvoice = 'clPurchaseTaxInvoice',
  clExternalBankOperationCodes = 'clExternalBankOperationCodes',
  clInternalBankOperationCodes = 'clInternalBankOperationCodes',
  clOutgoingExciseInvoice = 'clOutgoingExciseInvoice',
  clIncomingExciseInvoice = 'clIncomingExciseInvoice',
  clInventoryTransferRequests = 'clInventoryTransferRequests',
  clPurchaseQuotation = 'clPurchaseQuotation',
  clUDO = 'clUDO'
}
