export declare enum BoOperationEnum {
    rloNone = "rloNone",
    rloAddition = "rloAddition",
    rloSubtraction = "rloSubtraction",
    rloMultiplication = "rloMultiplication",
    rloDivision = "rloDivision",
    rloPercentage = "rloPercentage",
    rloLeftPartCharacters = "rloLeftPartCharacters",
    rloRightPartMantissa = "rloRightPartMantissa",
    rloRound = "rloRound",
    rloConcat = "rloConcat",
    rloRight = "rloRight",
    rloLeft = "rloLeft",
    rloSentence = "rloSentence",
    rloLength = "rloLength",
    rloCurrency = "rloCurrency",
    rloNumber = "rloNumber",
    rloLessThan = "rloLessThan",
    rloLessOrEqual = "rloLessOrEqual",
    rloEqual = "rloEqual",
    rloNotEqual = "rloNotEqual",
    rloGreaterOrEqual = "rloGreaterOrEqual",
    rloGreaterThan = "rloGreaterThan"
}
//# sourceMappingURL=BoOperationEnum.d.ts.map