/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */

export enum InventoryAccountTypeEnum {
  iatExpenses = 'iatExpenses',
  iatRevenues = 'iatRevenues',
  iatExemptIncome = 'iatExemptIncome',
  iatInventory = 'iatInventory',
  iatCost = 'iatCost',
  iatTransfer = 'iatTransfer',
  iatVarience = 'iatVarience',
  iatPriceDifference = 'iatPriceDifference',
  iatNegativeInventoryAdjustment = 'iatNegativeInventoryAdjustment',
  iatDecreasing = 'iatDecreasing',
  iatIncreasing = 'iatIncreasing',
  iatReturning = 'iatReturning',
  iatEURevenues = 'iatEURevenues',
  iatEUExpenses = 'iatEUExpenses',
  iatForeignRevenue = 'iatForeignRevenue',
  iatForeignExpens = 'iatForeignExpens',
  iatPurchase = 'iatPurchase',
  iatPAReturn = 'iatPAReturn',
  iatPurchaseOffset = 'iatPurchaseOffset',
  iatExchangeRateDifferences = 'iatExchangeRateDifferences',
  iatGoodsClearing = 'iatGoodsClearing',
  iatGLDecrease = 'iatGLDecrease',
  iatGLIncrease = 'iatGLIncrease',
  iatWip = 'iatWip',
  iatWipVariance = 'iatWipVariance',
  iatWipOffsetProfitAndLoss = 'iatWipOffsetProfitAndLoss',
  iatInventoryOffsetProfitAndLoss = 'iatInventoryOffsetProfitAndLoss',
  iatStockInflationAdjust = 'iatStockInflationAdjust',
  iatStockInflationOffset = 'iatStockInflationOffset',
  iatCostInflation = 'iatCostInflation',
  iatCostInflationOffset = 'iatCostInflationOffset',
  iatExpenseClearing = 'iatExpenseClearing',
  iatExpenseOffsetting = 'iatExpenseOffsetting',
  iatStockInTransit = 'iatStockInTransit',
  iatShippedGoods = 'iatShippedGoods',
  iatVATInRevenue = 'iatVATInRevenue',
  iatSalesCredit = 'iatSalesCredit',
  iatPurchaseCredit = 'iatPurchaseCredit',
  iatExemptedCredits = 'iatExemptedCredits',
  iatSalesCreditForeign = 'iatSalesCreditForeign',
  iatForeignPurchaseCredit = 'iatForeignPurchaseCredit',
  iatSalesCreditEU = 'iatSalesCreditEU',
  iatEUPurchaseCredit = 'iatEUPurchaseCredit',
  iatPurchaseBalance = 'iatPurchaseBalance',
  iatWHIncomingCenvat = 'iatWHIncomingCenvat',
  iatWHOutgoingCenvat = 'iatWHOutgoingCenvat',
  iatFreeOfChargeSales = 'iatFreeOfChargeSales',
  iatFreeOfChargePurchase = 'iatFreeOfChargePurchase'
}
